cc_binary(
    name="generator",
    srcs=["generator.cc"],
    deps = [
        "//src/google/protobuf",
		"//src/google/protobuf/compiler:importer",
        "@com_google_absl//absl/strings",
    ],
)